import type { Models } from 'node-appwrite';

// This file is auto-generated by the Appwrite CLI.
// You can regenerate it by running `appwrite types --language ts app/types`.

export enum TodosPriority {
    LOW = "low",
    MEDIUM = "medium",
    HIGH = "high"
}

export enum TodosStatus {
    BACKLOG = "backlog",
    TODAY = "today",
    UPCOMING = "upcoming",
    COMPLETED = "completed"
}

export type Todos = Models.Row & {
    title: string;
    description: string | null;
    dueDate: string | null;
    priority: TodosPriority;
    status: TodosStatus;
    parentId: string | null;
    userId: string;
    order: number;
}
